### ISSUE TITLE
Open DView instance will prevent eplusout.sql from being over-written

### ISSUE THREAD

**Issue by eringold** [NREL/wex#40] opened 2017-11-14 21:40 UTC
Reported in OpenStudio: https://github.com/NREL/OpenStudio/issues/2845

Might not require a change in DView, more in how OpenStudio is using it (per @macumber)

**Comment by shorowit** [comment] 2023-03-01 14:49
Duplicate of https://github.com/NREL/wex/issues/56, and that issue has more detail.

**Closed by shorowit** 2023-03-01 14:49 UTC
